repos:
-   repo: local
    hooks:
    -   id: ruff linter
        name: ruff linter
        language: system
        entry: bash -c "./scripts/run_with_local_venv.sh lint"
        types:
            - python
    -   id: ruff formatter
        name: ruff formatter
        language: system
        entry: bash -c "./scripts/run_with_local_venv.sh fmt"
        types:
            - python
    - id: mypy static type checker
      name: mypy static type checker
      language: system
      entry: bash -c "./scripts/run_with_local_venv.sh typing"
      types:
          - python