services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: on-failure

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    restart: on-failure