name: Test suite

on: push

jobs:
  setup:
    name: Configure environment
    uses: Matter-Tech/matter-library-actions/.github/workflows/run-tests.yaml@topic/make-setup-and-teardown-reusable-workflows

  run-tests:
    name: Run tests
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Set up test dependencies
        run: docker compose up -d

      - name: Running tests
        run: hatch run test:test

      - name: Tear down test dependencies
        run: docker compose down -v