name: Test suite

on: push

jobs:
  setup-test-dependencies:
    name: Set up Redis (and Postgres) instance
    uses: Matter-Tech/matter-library-actions/.github/workflows/setup-test-deps.yaml@topic/make-setup-and-teardown-reusable-workflows

  run-tests:
    name: Run tests
    uses: Matter-Tech/matter-library-actions/.github/workflows/run-tests.yaml@v2

  teardown-test-dependencies:
    name: Tear down Redis (and Postgres) instance
    uses: Matter-Tech/matter-library-actions/.github/workflows/teardown-test-deps.yaml@topic/make-setup-and-teardown-reusable-workflows