name: Test suite

on: push

jobs:
  run-test:
    runs-on: ubuntu-latest  # same as in the invoked workflow
    steps:
      - name: Set up testing environment (Redis instance)
        run: docker compose up -d

      - name: Run tests
        uses: Matter-Tech/matter-library-actions/.github/workflows/run-tests.yaml@v2

      - name: Tear down environment (Redis instance)
        run: docker compose down -v